### ISSUE TITLE
Is this project not supported any more???

### ISSUE THREAD

**Issue by randyhbh** [geofabrik/openstreetmap-carto-vector-tiles#3]

**Comment by amandasaurus** [comment]
No, What makes you think that?

**Comment by randyhbh** [comment]
I cant see any activity in 4 months.
Also i would like to know, if this style is compatible with the openmaptiles schema?

**Comment by amandasaurus** [comment]
The upstream osm-carto has released a new big change (v4.x) which I haven't ported to this yet. And I'm not sure *when* I will. So there's nothing new to be done for this project at the moment.

I haven't looked at the OpenMapTiles schema, but I don't think it's compatible. It would be an amazing probability if they had choosen the same layout.

**Comment by randyhbh** [comment]
So this layout who will be compatible? Mapbox schema?

**Comment by amandasaurus** [comment]
This project includes vector tile files, (MVT/pbfs), and also a style which displays them, like the regular osm-carto style

**Comment by randyhbh** [comment]
thanks for clarification!! :)
